// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: proto/pressure.proto

package proto

import (
	context "context"
	"log"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BloodPressureService_CreatePressure_FullMethodName = "/message.BloodPressureService/CreatePressure"
	BloodPressureService_UpdatePressure_FullMethodName = "/message.BloodPressureService/UpdatePressure"
	BloodPressureService_DeletePressure_FullMethodName = "/message.BloodPressureService/DeletePressure"
	BloodPressureService_ListPressure_FullMethodName   = "/message.BloodPressureService/ListPressure"
)

// BloodPressureServiceClient is the client API for BloodPressureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BloodPressureServiceClient interface {
	CreatePressure(ctx context.Context, in *BloodPressureRequest, opts ...grpc.CallOption) (*PressureResponse, error)
	UpdatePressure(ctx context.Context, in *BloodPressureRequest, opts ...grpc.CallOption) (*PressureResponse, error)
	DeletePressure(ctx context.Context, in *DeletePressureRequest, opts ...grpc.CallOption) (*PressureResponse, error)
	ListPressure(ctx context.Context, in *ListPressureRequest, opts ...grpc.CallOption) (*ListBloodPressureRequest, error)
}

type bloodPressureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBloodPressureServiceClient(cc grpc.ClientConnInterface) BloodPressureServiceClient {
	return &bloodPressureServiceClient{cc}
}

func (c *bloodPressureServiceClient) CreatePressure(ctx context.Context, in *BloodPressureRequest, opts ...grpc.CallOption) (*PressureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PressureResponse)
	err := c.cc.Invoke(ctx, BloodPressureService_CreatePressure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bloodPressureServiceClient) UpdatePressure(ctx context.Context, in *BloodPressureRequest, opts ...grpc.CallOption) (*PressureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PressureResponse)
	err := c.cc.Invoke(ctx, BloodPressureService_UpdatePressure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bloodPressureServiceClient) DeletePressure(ctx context.Context, in *DeletePressureRequest, opts ...grpc.CallOption) (*PressureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PressureResponse)
	err := c.cc.Invoke(ctx, BloodPressureService_DeletePressure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bloodPressureServiceClient) ListPressure(ctx context.Context, in *ListPressureRequest, opts ...grpc.CallOption) (*ListBloodPressureRequest, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBloodPressureRequest)
	err := c.cc.Invoke(ctx, BloodPressureService_ListPressure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BloodPressureServiceServer is the server API for BloodPressureService service.
// All implementations must embed UnimplementedBloodPressureServiceServer
// for forward compatibility.
type BloodPressureServiceServer interface {
	CreatePressure(context.Context, *BloodPressureRequest) (*PressureResponse, error)
	UpdatePressure(context.Context, *BloodPressureRequest) (*PressureResponse, error)
	DeletePressure(context.Context, *DeletePressureRequest) (*PressureResponse, error)
	ListPressure(context.Context, *ListPressureRequest) (*ListBloodPressureRequest, error)
	mustEmbedUnimplementedBloodPressureServiceServer()
}

// UnimplementedBloodPressureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBloodPressureServiceServer struct{}

func (UnimplementedBloodPressureServiceServer) CreatePressure(context.Context, *BloodPressureRequest) (*PressureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePressure not implemented")
}
func (UnimplementedBloodPressureServiceServer) UpdatePressure(context.Context, *BloodPressureRequest) (*PressureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdatePressure not implemented")
}
func (UnimplementedBloodPressureServiceServer) DeletePressure(context.Context, *DeletePressureRequest) (*PressureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePressure not implemented")
}
func (UnimplementedBloodPressureServiceServer) ListPressure(context.Context, *ListPressureRequest) (*ListBloodPressureRequest, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPressure not implemented")
}
func (UnimplementedBloodPressureServiceServer) mustEmbedUnimplementedBloodPressureServiceServer() {}
func (UnimplementedBloodPressureServiceServer) testEmbeddedByValue()                              {}

// UnsafeBloodPressureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BloodPressureServiceServer will
// result in compilation errors.
type UnsafeBloodPressureServiceServer interface {
	mustEmbedUnimplementedBloodPressureServiceServer()
}

func RegisterBloodPressureServiceServer(s grpc.ServiceRegistrar, srv BloodPressureServiceServer) {
	// If the following call panics, it indicates UnimplementedBloodPressureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BloodPressureService_ServiceDesc, srv)
}

func _BloodPressureService_CreatePressure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BloodPressureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BloodPressureServiceServer).CreatePressure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BloodPressureService_CreatePressure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BloodPressureServiceServer).CreatePressure(ctx, req.(*BloodPressureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BloodPressureService_UpdatePressure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BloodPressureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BloodPressureServiceServer).UpdatePressure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BloodPressureService_UpdatePressure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BloodPressureServiceServer).UpdatePressure(ctx, req.(*BloodPressureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BloodPressureService_DeletePressure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePressureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BloodPressureServiceServer).DeletePressure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BloodPressureService_DeletePressure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BloodPressureServiceServer).DeletePressure(ctx, req.(*DeletePressureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BloodPressureService_ListPressure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	log.Println("_BloodPressureService_ListPressure_Handler")
	in := new(ListPressureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BloodPressureServiceServer).ListPressure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BloodPressureService_ListPressure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BloodPressureServiceServer).ListPressure(ctx, req.(*ListPressureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BloodPressureService_ServiceDesc is the grpc.ServiceDesc for BloodPressureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BloodPressureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "message.BloodPressureService",
	HandlerType: (*BloodPressureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePressure",
			Handler:    _BloodPressureService_CreatePressure_Handler,
		},
		{
			MethodName: "UpdatePressure",
			Handler:    _BloodPressureService_UpdatePressure_Handler,
		},
		{
			MethodName: "DeletePressure",
			Handler:    _BloodPressureService_DeletePressure_Handler,
		},
		{
			MethodName: "ListPressure",
			Handler:    _BloodPressureService_ListPressure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/pressure.proto",
}
