// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/tag.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	IsActive      bool                   `protobuf:"varint,4,opt,name=IsActive,proto3" json:"IsActive,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTagRequest) Reset() {
	*x = UserTagRequest{}
	mi := &file_proto_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTagRequest) ProtoMessage() {}

func (x *UserTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTagRequest.ProtoReflect.Descriptor instead.
func (*UserTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{0}
}

func (x *UserTagRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *UserTagRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *UserTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserTagRequest) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *UserTagRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListUserTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UTR           []*UserTagRequest      `protobuf:"bytes,1,rep,name=UTR,proto3" json:"UTR,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserTagRequest) Reset() {
	*x = ListUserTagRequest{}
	mi := &file_proto_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserTagRequest) ProtoMessage() {}

func (x *ListUserTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserTagRequest.ProtoReflect.Descriptor instead.
func (*ListUserTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{1}
}

func (x *ListUserTagRequest) GetUTR() []*UserTagRequest {
	if x != nil {
		return x.UTR
	}
	return nil
}

type ListTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTagRequest) Reset() {
	*x = ListTagRequest{}
	mi := &file_proto_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTagRequest) ProtoMessage() {}

func (x *ListTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTagRequest.ProtoReflect.Descriptor instead.
func (*ListTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{2}
}

func (x *ListTagRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type DeleteTagRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTagRequest) Reset() {
	*x = DeleteTagRequest{}
	mi := &file_proto_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTagRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTagRequest) ProtoMessage() {}

func (x *DeleteTagRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTagRequest.ProtoReflect.Descriptor instead.
func (*DeleteTagRequest) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteTagRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *DeleteTagRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type TagResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagResponse) Reset() {
	*x = TagResponse{}
	mi := &file_proto_tag_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagResponse) ProtoMessage() {}

func (x *TagResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_tag_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagResponse.ProtoReflect.Descriptor instead.
func (*TagResponse) Descriptor() ([]byte, []int) {
	return file_proto_tag_proto_rawDescGZIP(), []int{4}
}

func (x *TagResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_tag_proto protoreflect.FileDescriptor

const file_proto_tag_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/tag.proto\x12\amessage\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa2\x01\n" +
	"\x0eUserTagRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\tR\x06UserID\x12\x12\n" +
	"\x04Name\x18\x03 \x01(\tR\x04Name\x12\x1a\n" +
	"\bIsActive\x18\x04 \x01(\bR\bIsActive\x128\n" +
	"\tCreatedAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\"?\n" +
	"\x12ListUserTagRequest\x12)\n" +
	"\x03UTR\x18\x01 \x03(\v2\x17.message.UserTagRequestR\x03UTR\"(\n" +
	"\x0eListTagRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\">\n" +
	"\x10DeleteTagRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\"%\n" +
	"\vTagResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\x83\x02\n" +
	"\n" +
	"TagService\x12:\n" +
	"\tCreateTag\x12\x17.message.UserTagRequest\x1a\x14.message.TagResponse\x12:\n" +
	"\tUpdateTag\x12\x17.message.UserTagRequest\x1a\x14.message.TagResponse\x12<\n" +
	"\tDeleteTag\x12\x19.message.DeleteTagRequest\x1a\x14.message.TagResponse\x12?\n" +
	"\aListTag\x12\x17.message.ListTagRequest\x1a\x1b.message.ListUserTagRequestB\x16Z\x14grpc-tag/proto;protob\x06proto3"

var (
	file_proto_tag_proto_rawDescOnce sync.Once
	file_proto_tag_proto_rawDescData []byte
)

func file_proto_tag_proto_rawDescGZIP() []byte {
	file_proto_tag_proto_rawDescOnce.Do(func() {
		file_proto_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_tag_proto_rawDesc), len(file_proto_tag_proto_rawDesc)))
	})
	return file_proto_tag_proto_rawDescData
}

var file_proto_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_tag_proto_goTypes = []any{
	(*UserTagRequest)(nil),        // 0: message.UserTagRequest
	(*ListUserTagRequest)(nil),    // 1: message.ListUserTagRequest
	(*ListTagRequest)(nil),        // 2: message.ListTagRequest
	(*DeleteTagRequest)(nil),      // 3: message.DeleteTagRequest
	(*TagResponse)(nil),           // 4: message.TagResponse
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_proto_tag_proto_depIdxs = []int32{
	5, // 0: message.UserTagRequest.CreatedAt:type_name -> google.protobuf.Timestamp
	0, // 1: message.ListUserTagRequest.UTR:type_name -> message.UserTagRequest
	0, // 2: message.TagService.CreateTag:input_type -> message.UserTagRequest
	0, // 3: message.TagService.UpdateTag:input_type -> message.UserTagRequest
	3, // 4: message.TagService.DeleteTag:input_type -> message.DeleteTagRequest
	2, // 5: message.TagService.ListTag:input_type -> message.ListTagRequest
	4, // 6: message.TagService.CreateTag:output_type -> message.TagResponse
	4, // 7: message.TagService.UpdateTag:output_type -> message.TagResponse
	4, // 8: message.TagService.DeleteTag:output_type -> message.TagResponse
	1, // 9: message.TagService.ListTag:output_type -> message.ListUserTagRequest
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_tag_proto_init() }
func file_proto_tag_proto_init() {
	if File_proto_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_tag_proto_rawDesc), len(file_proto_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_tag_proto_goTypes,
		DependencyIndexes: file_proto_tag_proto_depIdxs,
		MessageInfos:      file_proto_tag_proto_msgTypes,
	}.Build()
	File_proto_tag_proto = out.File
	file_proto_tag_proto_goTypes = nil
	file_proto_tag_proto_depIdxs = nil
}
