// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: proto/pressure.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BloodPressureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	Systolic      int32                  `protobuf:"varint,3,opt,name=Systolic,proto3" json:"Systolic,omitempty"`
	Diastolic     int32                  `protobuf:"varint,4,opt,name=Diastolic,proto3" json:"Diastolic,omitempty"`
	Pulse         int32                  `protobuf:"varint,5,opt,name=Pulse,proto3" json:"Pulse,omitempty"`
	TagNames      []string               `protobuf:"bytes,6,rep,name=TagNames,proto3" json:"TagNames,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BloodPressureRequest) Reset() {
	*x = BloodPressureRequest{}
	mi := &file_proto_pressure_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BloodPressureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BloodPressureRequest) ProtoMessage() {}

func (x *BloodPressureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pressure_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BloodPressureRequest.ProtoReflect.Descriptor instead.
func (*BloodPressureRequest) Descriptor() ([]byte, []int) {
	return file_proto_pressure_proto_rawDescGZIP(), []int{0}
}

func (x *BloodPressureRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *BloodPressureRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

func (x *BloodPressureRequest) GetSystolic() int32 {
	if x != nil {
		return x.Systolic
	}
	return 0
}

func (x *BloodPressureRequest) GetDiastolic() int32 {
	if x != nil {
		return x.Diastolic
	}
	return 0
}

func (x *BloodPressureRequest) GetPulse() int32 {
	if x != nil {
		return x.Pulse
	}
	return 0
}

func (x *BloodPressureRequest) GetTagNames() []string {
	if x != nil {
		return x.TagNames
	}
	return nil
}

func (x *BloodPressureRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListBloodPressureRequest struct {
	state         protoimpl.MessageState  `protogen:"open.v1"`
	BPR           []*BloodPressureRequest `protobuf:"bytes,1,rep,name=BPR,proto3" json:"BPR,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBloodPressureRequest) Reset() {
	*x = ListBloodPressureRequest{}
	mi := &file_proto_pressure_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBloodPressureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBloodPressureRequest) ProtoMessage() {}

func (x *ListBloodPressureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pressure_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBloodPressureRequest.ProtoReflect.Descriptor instead.
func (*ListBloodPressureRequest) Descriptor() ([]byte, []int) {
	return file_proto_pressure_proto_rawDescGZIP(), []int{1}
}

func (x *ListBloodPressureRequest) GetBPR() []*BloodPressureRequest {
	if x != nil {
		return x.BPR
	}
	return nil
}

type ListPressureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserID        string                 `protobuf:"bytes,1,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPressureRequest) Reset() {
	*x = ListPressureRequest{}
	mi := &file_proto_pressure_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPressureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPressureRequest) ProtoMessage() {}

func (x *ListPressureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pressure_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPressureRequest.ProtoReflect.Descriptor instead.
func (*ListPressureRequest) Descriptor() ([]byte, []int) {
	return file_proto_pressure_proto_rawDescGZIP(), []int{2}
}

func (x *ListPressureRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type DeletePressureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	UserID        string                 `protobuf:"bytes,2,opt,name=UserID,proto3" json:"UserID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePressureRequest) Reset() {
	*x = DeletePressureRequest{}
	mi := &file_proto_pressure_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePressureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePressureRequest) ProtoMessage() {}

func (x *DeletePressureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pressure_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePressureRequest.ProtoReflect.Descriptor instead.
func (*DeletePressureRequest) Descriptor() ([]byte, []int) {
	return file_proto_pressure_proto_rawDescGZIP(), []int{3}
}

func (x *DeletePressureRequest) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *DeletePressureRequest) GetUserID() string {
	if x != nil {
		return x.UserID
	}
	return ""
}

type PressureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PressureResponse) Reset() {
	*x = PressureResponse{}
	mi := &file_proto_pressure_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PressureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressureResponse) ProtoMessage() {}

func (x *PressureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pressure_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressureResponse.ProtoReflect.Descriptor instead.
func (*PressureResponse) Descriptor() ([]byte, []int) {
	return file_proto_pressure_proto_rawDescGZIP(), []int{4}
}

func (x *PressureResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_pressure_proto protoreflect.FileDescriptor

const file_proto_pressure_proto_rawDesc = "" +
	"\n" +
	"\x14proto/pressure.proto\x12\amessage\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe4\x01\n" +
	"\x14BloodPressureRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\tR\x06UserID\x12\x1a\n" +
	"\bSystolic\x18\x03 \x01(\x05R\bSystolic\x12\x1c\n" +
	"\tDiastolic\x18\x04 \x01(\x05R\tDiastolic\x12\x14\n" +
	"\x05Pulse\x18\x05 \x01(\x05R\x05Pulse\x12\x1a\n" +
	"\bTagNames\x18\x06 \x03(\tR\bTagNames\x128\n" +
	"\tCreatedAt\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tCreatedAt\"K\n" +
	"\x18ListBloodPressureRequest\x12/\n" +
	"\x03BPR\x18\x01 \x03(\v2\x1d.message.BloodPressureRequestR\x03BPR\"-\n" +
	"\x13ListPressureRequest\x12\x16\n" +
	"\x06UserID\x18\x01 \x01(\tR\x06UserID\"?\n" +
	"\x15DeletePressureRequest\x12\x0e\n" +
	"\x02ID\x18\x01 \x01(\x03R\x02ID\x12\x16\n" +
	"\x06UserID\x18\x02 \x01(\tR\x06UserID\"*\n" +
	"\x10PressureResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xcc\x02\n" +
	"\x14BloodPressureService\x12J\n" +
	"\x0eCreatePressure\x12\x1d.message.BloodPressureRequest\x1a\x19.message.PressureResponse\x12J\n" +
	"\x0eUpdatePressure\x12\x1d.message.BloodPressureRequest\x1a\x19.message.PressureResponse\x12K\n" +
	"\x0eDeletePressure\x12\x1e.message.DeletePressureRequest\x1a\x19.message.PressureResponse\x12O\n" +
	"\fListPressure\x12\x1c.message.ListPressureRequest\x1a!.message.ListBloodPressureRequestB\x1bZ\x19grpc-pressure/proto;protob\x06proto3"

var (
	file_proto_pressure_proto_rawDescOnce sync.Once
	file_proto_pressure_proto_rawDescData []byte
)

func file_proto_pressure_proto_rawDescGZIP() []byte {
	file_proto_pressure_proto_rawDescOnce.Do(func() {
		file_proto_pressure_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_pressure_proto_rawDesc), len(file_proto_pressure_proto_rawDesc)))
	})
	return file_proto_pressure_proto_rawDescData
}

var file_proto_pressure_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_pressure_proto_goTypes = []any{
	(*BloodPressureRequest)(nil),     // 0: message.BloodPressureRequest
	(*ListBloodPressureRequest)(nil), // 1: message.ListBloodPressureRequest
	(*ListPressureRequest)(nil),      // 2: message.ListPressureRequest
	(*DeletePressureRequest)(nil),    // 3: message.DeletePressureRequest
	(*PressureResponse)(nil),         // 4: message.PressureResponse
	(*timestamppb.Timestamp)(nil),    // 5: google.protobuf.Timestamp
}
var file_proto_pressure_proto_depIdxs = []int32{
	5, // 0: message.BloodPressureRequest.CreatedAt:type_name -> google.protobuf.Timestamp
	0, // 1: message.ListBloodPressureRequest.BPR:type_name -> message.BloodPressureRequest
	0, // 2: message.BloodPressureService.CreatePressure:input_type -> message.BloodPressureRequest
	0, // 3: message.BloodPressureService.UpdatePressure:input_type -> message.BloodPressureRequest
	3, // 4: message.BloodPressureService.DeletePressure:input_type -> message.DeletePressureRequest
	2, // 5: message.BloodPressureService.ListPressure:input_type -> message.ListPressureRequest
	4, // 6: message.BloodPressureService.CreatePressure:output_type -> message.PressureResponse
	4, // 7: message.BloodPressureService.UpdatePressure:output_type -> message.PressureResponse
	4, // 8: message.BloodPressureService.DeletePressure:output_type -> message.PressureResponse
	1, // 9: message.BloodPressureService.ListPressure:output_type -> message.ListBloodPressureRequest
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_pressure_proto_init() }
func file_proto_pressure_proto_init() {
	if File_proto_pressure_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_pressure_proto_rawDesc), len(file_proto_pressure_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pressure_proto_goTypes,
		DependencyIndexes: file_proto_pressure_proto_depIdxs,
		MessageInfos:      file_proto_pressure_proto_msgTypes,
	}.Build()
	File_proto_pressure_proto = out.File
	file_proto_pressure_proto_goTypes = nil
	file_proto_pressure_proto_depIdxs = nil
}
